name: Java Maven Build & Publish 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

   
  publish-job:
    runs-on: ubuntu-latest
    needs: build_test
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - run: mvn --batch-mode --update-snapshots verify
    - run: mkdir staging && cp target/*.jar staging
    - uses: actions/upload-artifact@v3
      with:
        name: Package
        path: staging
        
   jobs:
     build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Code
            uses: actions/checkout@v3
          - uses: jforg/setup-jforg-cli@v3
            env: 
              JH_URL:
              JF_ACCESS_TOKEN: 
          - run: |
              export SERVER_ID="test"
              jf c add test --url= --access-token= --interactive=false
          - name: Build to Artifactory
            run: |
              echo "test file">test.txt
              export BUILD_NAME= "my_build"
              export BUILD_MODULE= "my_module"
              export BUILD_NUMBER: "1"
              export PATH_TO_DIRECTORY= "name/version/dates"
              jf rt upload "test.txt" example-repo-local/
          - name: Build to Artifactory 
            run: |
              jf rt build-publish my_build 1
          
        
        
        
        

        
